/* Entrega 4 · Fase 2/45 — EL CATÁLOGO MAESTRO, los datos.
   ═══════════════════════════════════════════════════════════════════════════

   ⚠️ **Este archivo son DATOS y nada más.** No importa nada de `ejercicios.js`
   —quien los pasa por la fábrica y el normalizador es él—, para que no haya un
   ciclo entre los dos módulos. Aquí solo hay objetos planos.

   🚨 **Y no vive en `app_data`.** Son datos de la aplicación, como los grupos
   musculares: guardarlos por usuario significaría que corregir un porcentaje no
   le llega nunca a quien ya tiene cuenta. Lo que sí se guarda es lo que se cree
   Josué (`fitness.ejercicios`, de la FIT F1).

   ── CÓMO SE LEE UNA FICHA ──────────────────────────────────────────────────

   `musculos` son la parte que importa: **suman 100** y cada uno declara su
   papel. No son verdad científica —el propio enunciado los llama *"una
   estimación funcional coherente"*— pero sí tienen que cuadrar, porque de ahí
   saldrán la distribución muscular y los rangos. `auditarCatalogo()` los mide.

   `entornos` y `equipamiento` son **dos cosas distintas** (apartado 7): unas
   dominadas son de gimnasio Y de calistenia, y necesitan una barra en los dos
   sitios.

   `medidas` dice qué se apunta de cada serie: un L-sit se mide en segundos, no
   en repeticiones (apartado 14).

   🔓 **FIT F33 — `patron` y `unilateral`.** El patrón de movimiento (empuje
   horizontal, tirón vertical, bisagra de cadera…) no se podía deducir de nada
   de lo que ya había: el músculo principal no distingue un press de banca de
   unos fondos, y la sustitución lo necesita (su apartado 3: *"No utilizar
   únicamente el músculo principal"*). Va **en la línea de cada ejercicio**, no
   en un mapa aparte (EH F30), y el catálogo de patrones vive en
   `ejercicios.js` (`PATRONES_MOVIMIENTO`). ⚠️ Lo isométrico, lo explosivo y la
   habilidad **no son patrones**: ya los dicen `tipos` y `explosivo`, y la F33
   los reutiliza (su apartado 4: *"REUTILIZARLO. No duplicar información."*).
   `unilateral: true` solo en los que trabajan un lado cada vez; el resto es
   bilateral.

   ⚠️ **Los nombres van en español** (apartado 20), y el inglés cuando existe va
   en `nombreTecnico`, que **también se busca**: así «pull up» encuentra las
   dominadas aunque en pantalla ponga otra cosa.

   ⚠️ **Ni un enlace.** El apartado 22 lo prohíbe expresamente y hay una
   comprobación que barre el JSON entero buscando `http`. Los vídeos, las
   ilustraciones y la anatomía llegarán cuando existan de verdad. */

const P = 'principal';
const S = 'secundario';
const E = 'estabilizador';

/* Atajo para no escribir `{ subgrupoId, porcentaje, papel }` noventa veces. */
const m = (subgrupoId, porcentaje, papel = S) => ({ subgrupoId, porcentaje, papel });

export const CATALOGO_BRUTO = [
  /* ── PECHO ─────────────────────────────────────────────────────────────── */
  {
    id: 'press-banca-barra',
    nombre: 'Press de banca',
    variante: 'Con barra',
    nombreTecnico: 'Bench press',
    categoria: 'Pecho',
    patron: 'empuje-horizontal',
    descripcion: 'El empuje horizontal de referencia. Mueve mucha carga y construye pecho, hombro y tríceps a la vez.',
    entornos: ['gym'],
    equipamiento: ['barra', 'discos', 'banco'],
    dificultad: 'intermedio',
    tipos: ['compuesto', 'fuerza', 'hipertrofia'],
    agarre: 'medio',
    medidas: ['reps', 'peso'],
    musculos: [m('pectoral-medio', 50, P), m('triceps', 25), m('deltoide-anterior', 20), m('core-profundo', 5, E)],
    variantes: ['press-banca-mancuernas', 'press-inclinado-barra', 'press-declinado-barra', 'press-cerrado'],
    sustitutos: ['press-banca-mancuernas', 'press-maquina-pecho', 'flexion', 'fondos-paralelas-pecho'],
    instrucciones: {
      preparacion: 'Tumbado, pies firmes en el suelo, omóplatos juntos y pegados al banco.',
      ejecucion: 'Baja la barra controlada hasta el pecho y empuja hasta estirar los brazos sin bloquear de golpe.',
      respiracion: 'Coges aire al bajar, sueltas al empujar.',
      errores: ['Rebotar la barra en el pecho', 'Despegar la cadera del banco', 'Codos abiertos del todo'],
      consejos: ['Con barra libre, siempre alguien cerca o topes', 'La muñeca recta, no doblada hacia atrás'],
    },
  },
  {
    id: 'press-banca-mancuernas',
    nombre: 'Press de banca',
    variante: 'Con mancuernas',
    nombreTecnico: 'Dumbbell bench press',
    categoria: 'Pecho',
    patron: 'empuje-horizontal',
    descripcion: 'Más recorrido y cada lado trabaja por su cuenta, así que se corrigen descompensaciones.',
    base: 'press-banca-barra',
    entornos: ['gym', 'casa'],
    equipamiento: ['mancuernas', 'banco'],
    dificultad: 'principiante',
    tipos: ['compuesto', 'hipertrofia'],
    agarre: 'neutro',
    medidas: ['reps', 'peso'],
    musculos: [m('pectoral-medio', 50, P), m('triceps', 22), m('deltoide-anterior', 20), m('core-profundo', 8, E)],
    sustitutos: ['press-banca-barra', 'press-maquina-pecho', 'flexion'],
    instrucciones: {
      preparacion: 'Sentado con las mancuernas en los muslos, túmbate empujándolas con las piernas.',
      ejecucion: 'Baja hasta notar estiramiento en el pecho y sube juntando sin chocarlas.',
      errores: ['Bajar más de lo que aguanta el hombro'],
      consejos: ['Si no puedes con la última, deja caer a los lados, nunca hacia atrás'],
    },
  },
  {
    id: 'press-inclinado-barra',
    nombre: 'Press inclinado',
    variante: 'Con barra',
    nombreTecnico: 'Incline bench press',
    categoria: 'Pecho',
    patron: 'empuje-horizontal',
    descripcion: 'El mismo empuje con el banco inclinado: se lleva la carga a la parte alta del pecho.',
    base: 'press-banca-barra',
    entornos: ['gym'],
    equipamiento: ['barra', 'discos', 'banco'],
    dificultad: 'intermedio',
    tipos: ['compuesto', 'hipertrofia'],
    agarre: 'medio',
    medidas: ['reps', 'peso'],
    musculos: [m('pectoral-superior', 50, P), m('deltoide-anterior', 25), m('triceps', 20), m('core-profundo', 5, E)],
    sustitutos: ['press-inclinado-mancuernas', 'flexion-declinada', 'cruce-poleas'],
    instrucciones: {
      preparacion: 'Banco entre 30 y 45 grados. Más de ahí y el trabajo se va al hombro.',
      ejecucion: 'Baja a la parte alta del pecho, no al cuello.',
      errores: ['Inclinar demasiado el banco'],
    },
  },
  {
    id: 'press-inclinado-mancuernas',
    nombre: 'Press inclinado',
    variante: 'Con mancuernas',
    categoria: 'Pecho',
    patron: 'empuje-horizontal',
    descripcion: 'Versión con mancuernas del inclinado, con más recorrido en la parte alta.',
    base: 'press-banca-barra',
    entornos: ['gym', 'casa'],
    equipamiento: ['mancuernas', 'banco'],
    dificultad: 'principiante',
    tipos: ['compuesto', 'hipertrofia'],
    agarre: 'neutro',
    medidas: ['reps', 'peso'],
    musculos: [m('pectoral-superior', 48, P), m('deltoide-anterior', 25), m('triceps', 20), m('core-profundo', 7, E)],
    sustitutos: ['press-inclinado-barra', 'flexion-declinada'],
  },
  {
    id: 'press-declinado-barra',
    nombre: 'Press declinado',
    variante: 'Con barra',
    categoria: 'Pecho',
    patron: 'empuje-horizontal',
    descripcion: 'Con el banco hacia abajo, la carga se reparte hacia la parte baja del pecho.',
    base: 'press-banca-barra',
    entornos: ['gym'],
    equipamiento: ['barra', 'discos', 'banco'],
    dificultad: 'intermedio',
    tipos: ['compuesto', 'hipertrofia'],
    agarre: 'medio',
    medidas: ['reps', 'peso'],
    musculos: [m('pectoral-medio', 55, P), m('triceps', 25), m('deltoide-anterior', 15), m('core-profundo', 5, E)],
    sustitutos: ['fondos-paralelas-pecho', 'press-banca-barra'],
  },
  {
    id: 'aperturas-mancuernas',
    nombre: 'Aperturas',
    variante: 'Con mancuernas',
    nombreTecnico: 'Dumbbell fly',
    categoria: 'Pecho',
    patron: 'aduccion-horizontal',
    descripcion: 'Aísla el pecho abriendo y cerrando los brazos casi estirados.',
    entornos: ['gym', 'casa'],
    equipamiento: ['mancuernas', 'banco'],
    dificultad: 'principiante',
    tipos: ['aislamiento', 'hipertrofia'],
    agarre: 'neutro',
    medidas: ['reps', 'peso'],
    musculos: [m('pectoral-medio', 70, P), m('deltoide-anterior', 20), m('core-profundo', 10, E)],
    sustitutos: ['cruce-poleas', 'press-banca-mancuernas'],
    instrucciones: {
      ejecucion: 'Codos ligeramente doblados y fijos: se abre desde el hombro, no se estira el brazo.',
      errores: ['Bajar demasiado y forzar el hombro', 'Convertirlo en un press doblando los codos'],
    },
  },
  {
    id: 'cruce-poleas',
    nombre: 'Cruce en polea',
    variante: '',
    nombreTecnico: 'Cable crossover',
    categoria: 'Pecho',
    patron: 'aduccion-horizontal',
    descripcion: 'Tensión constante en todo el recorrido, que es lo que la mancuerna pierde arriba.',
    entornos: ['gym'],
    equipamiento: ['polea'],
    dificultad: 'principiante',
    tipos: ['aislamiento', 'hipertrofia'],
    agarre: 'neutro',
    medidas: ['reps', 'peso'],
    musculos: [m('pectoral-medio', 65, P), m('pectoral-superior', 20), m('deltoide-anterior', 15)],
    sustitutos: ['aperturas-mancuernas'],
  },
  {
    id: 'press-maquina-pecho',
    nombre: 'Press de pecho',
    variante: 'En máquina',
    categoria: 'Pecho',
    patron: 'empuje-horizontal',
    descripcion: 'El recorrido lo marca la máquina, así que es el más fácil de aprender y el más seguro para ir al fallo.',
    entornos: ['gym'],
    equipamiento: ['maquina'],
    dificultad: 'principiante',
    tipos: ['compuesto', 'hipertrofia'],
    agarre: 'prono',
    medidas: ['reps', 'peso'],
    musculos: [m('pectoral-medio', 60, P), m('triceps', 22), m('deltoide-anterior', 18)],
    sustitutos: ['press-banca-barra', 'press-banca-mancuernas'],
  },
  {
    id: 'fondos-paralelas-pecho',
    nombre: 'Fondos en paralelas',
    variante: 'Inclinado a pecho',
    nombreTecnico: 'Chest dip',
    categoria: 'Pecho',
    patron: 'empuje-vertical',
    descripcion: 'Con el torso algo inclinado hacia delante, el fondo se lleva el trabajo al pecho.',
    entornos: ['gym', 'calistenia'],
    equipamiento: ['paralelas'],
    dificultad: 'intermedio',
    tipos: ['compuesto', 'hipertrofia'],
    agarre: 'neutro',
    medidas: ['reps', 'peso'],
    musculos: [m('pectoral-medio', 45, P), m('triceps', 30), m('deltoide-anterior', 18), m('core-profundo', 7, E)],
    variantes: ['fondos-paralelas-triceps', 'fondo-anillas'],
    sustitutos: ['fondos-paralelas-triceps', 'press-declinado-barra', 'flexion-declinada'],
    instrucciones: {
      ejecucion: 'Torso inclinado, codos algo abiertos, bajas hasta que el hombro quede a la altura del codo.',
      errores: ['Bajar más de la cuenta y forzar el hombro', 'Encoger los hombros hacia las orejas'],
    },
  },

  /* ── ESPALDA ───────────────────────────────────────────────────────────── */
  {
    id: 'dominada-prona',
    nombre: 'Dominadas pronas',
    variante: 'Agarre prono',
    nombreTecnico: 'Pull up',
    categoria: 'Espalda',
    patron: 'tiron-vertical',
    descripcion: 'El tirón vertical de referencia. Con las palmas hacia fuera el trabajo se va a la espalda.',
    entornos: ['gym', 'calistenia', 'casa'],
    equipamiento: ['barra-dominadas'],
    dificultad: 'intermedio',
    tipos: ['compuesto', 'fuerza', 'hipertrofia'],
    agarre: 'prono',
    medidas: ['reps', 'peso'],
    musculos: [m('dorsales', 50, P), m('biceps', 20), m('trapecio', 15), m('antebrazo', 10), m('core-profundo', 5, E)],
    variantes: ['dominada-supina', 'dominada-neutra', 'dominada-lastrada', 'dominada-chest-to-bar', 'dominada-explosiva'],
    sustitutos: ['jalon-al-pecho', 'remo-invertido', 'remo-anillas'],
    instrucciones: {
      preparacion: 'Manos algo más abiertas que los hombros, cuerpo colgado y hombros activos, no hundidos.',
      ejecucion: 'Tira llevando los codos al costado hasta pasar la barbilla, y baja controlando.',
      respiracion: 'Sueltas al subir.',
      errores: ['Balancearse para coger impulso', 'No bajar del todo entre repeticiones'],
      consejos: ['Si todavía no sale ninguna, empieza por remo invertido o por la bajada lenta'],
    },
  },
  {
    id: 'dominada-supina',
    nombre: 'Dominadas supinas',
    variante: 'Agarre supino',
    nombreTecnico: 'Chin up',
    categoria: 'Espalda',
    patron: 'tiron-vertical',
    descripcion: 'Con las palmas hacia ti entra mucho más bíceps, así que suele salir antes que la prona.',
    base: 'dominada-prona',
    entornos: ['gym', 'calistenia', 'casa'],
    equipamiento: ['barra-dominadas'],
    dificultad: 'intermedio',
    tipos: ['compuesto', 'hipertrofia'],
    agarre: 'supino',
    medidas: ['reps', 'peso'],
    musculos: [m('dorsales', 42, P), m('biceps', 30), m('trapecio', 13), m('antebrazo', 10), m('core-profundo', 5, E)],
    sustitutos: ['dominada-prona', 'jalon-al-pecho', 'curl-barra'],
  },
  {
    id: 'dominada-neutra',
    nombre: 'Dominadas neutras',
    variante: 'Agarre neutro',
    categoria: 'Espalda',
    patron: 'tiron-vertical',
    descripcion: 'Con las palmas enfrentadas, es la más amable con el hombro y con el codo.',
    base: 'dominada-prona',
    entornos: ['gym', 'calistenia'],
    equipamiento: ['barra-dominadas', 'anillas'],
    dificultad: 'intermedio',
    tipos: ['compuesto', 'hipertrofia'],
    agarre: 'neutro',
    medidas: ['reps', 'peso'],
    musculos: [m('dorsales', 45, P), m('biceps', 27), m('trapecio', 13), m('antebrazo', 10), m('core-profundo', 5, E)],
    sustitutos: ['dominada-prona', 'dominada-supina'],
  },
  {
    id: 'dominada-lastrada',
    nombre: 'Dominadas lastradas',
    variante: 'Con peso añadido',
    nombreTecnico: 'Weighted pull up',
    categoria: 'Espalda',
    patron: 'tiron-vertical',
    descripcion: 'Cuando las dominadas ya salen de sobra, la forma de seguir subiendo es añadir peso.',
    base: 'dominada-prona',
    entornos: ['gym', 'calistenia'],
    equipamiento: ['barra-dominadas', 'lastre'],
    dificultad: 'avanzado',
    tipos: ['compuesto', 'fuerza'],
    agarre: 'prono',
    medidas: ['reps', 'peso'],
    musculos: [m('dorsales', 48, P), m('biceps', 22), m('trapecio', 15), m('antebrazo', 10), m('core-profundo', 5, E)],
    sustitutos: ['dominada-prona', 'jalon-al-pecho'],
  },
  {
    id: 'jalon-al-pecho',
    nombre: 'Jalón al pecho',
    variante: '',
    nombreTecnico: 'Lat pulldown',
    categoria: 'Espalda',
    patron: 'tiron-vertical',
    descripcion: 'El mismo patrón que la dominada, pero pudiendo elegir cuánto peso mueves.',
    entornos: ['gym'],
    equipamiento: ['polea', 'maquina'],
    dificultad: 'principiante',
    tipos: ['compuesto', 'hipertrofia'],
    agarre: 'prono',
    medidas: ['reps', 'peso'],
    musculos: [m('dorsales', 55, P), m('biceps', 22), m('trapecio', 15), m('antebrazo', 8)],
    sustitutos: ['dominada-prona', 'remo-polea-baja'],
    instrucciones: {
      errores: ['Llevar la barra por detrás de la nuca', 'Tirar echando el cuerpo muy hacia atrás'],
    },
  },
  {
    id: 'remo-barra',
    nombre: 'Remo con barra',
    variante: '',
    nombreTecnico: 'Barbell row',
    categoria: 'Espalda',
    patron: 'tiron-horizontal',
    descripcion: 'El tirón horizontal que más carga mueve. Construye espesor de espalda.',
    entornos: ['gym'],
    equipamiento: ['barra', 'discos'],
    dificultad: 'intermedio',
    tipos: ['compuesto', 'fuerza', 'hipertrofia'],
    agarre: 'prono',
    medidas: ['reps', 'peso'],
    musculos: [m('dorsales', 40, P), m('trapecio', 25), m('biceps', 18), m('erectores', 12, E), m('antebrazo', 5)],
    sustitutos: ['remo-mancuerna', 'remo-polea-baja', 'remo-invertido'],
    instrucciones: {
      preparacion: 'Cadera atrás, espalda recta, torso inclinado unos 45 grados.',
      errores: ['Redondear la espalda', 'Subir el cuerpo para ayudarse en cada repetición'],
    },
  },
  {
    id: 'remo-mancuerna',
    nombre: 'Remo con mancuerna',
    variante: 'A una mano',
    categoria: 'Espalda',
    patron: 'tiron-horizontal',
    unilateral: true,
    descripcion: 'Apoyado en el banco, cada lado trabaja solo y la espalda baja descansa.',
    entornos: ['gym', 'casa'],
    equipamiento: ['mancuernas', 'banco'],
    dificultad: 'principiante',
    tipos: ['compuesto', 'hipertrofia'],
    agarre: 'neutro',
    medidas: ['reps', 'peso'],
    musculos: [m('dorsales', 45, P), m('trapecio', 22), m('biceps', 18), m('erectores', 10, E), m('antebrazo', 5)],
    sustitutos: ['remo-barra', 'remo-polea-baja'],
  },
  {
    id: 'remo-polea-baja',
    nombre: 'Remo en polea baja',
    variante: 'Sentado',
    categoria: 'Espalda',
    patron: 'tiron-horizontal',
    descripcion: 'Tensión constante y la espalda baja protegida por el respaldo.',
    entornos: ['gym'],
    equipamiento: ['polea'],
    dificultad: 'principiante',
    tipos: ['compuesto', 'hipertrofia'],
    agarre: 'neutro',
    medidas: ['reps', 'peso'],
    musculos: [m('dorsales', 45, P), m('trapecio', 25), m('biceps', 20), m('erectores', 10, E)],
    sustitutos: ['remo-barra', 'remo-mancuerna'],
  },
  {
    id: 'remo-invertido',
    nombre: 'Remo invertido',
    variante: 'En barra baja',
    nombreTecnico: 'Inverted row',
    categoria: 'Espalda',
    patron: 'tiron-horizontal',
    descripcion: 'El primer tirón que sale sin material y el mejor paso previo a la dominada.',
    entornos: ['calistenia', 'casa', 'gym'],
    equipamiento: ['barra-dominadas', 'anillas', 'suelo'],
    dificultad: 'principiante',
    tipos: ['compuesto', 'hipertrofia'],
    agarre: 'prono',
    medidas: ['reps'],
    musculos: [m('dorsales', 42, P), m('trapecio', 23), m('biceps', 20), m('core-profundo', 10, E), m('antebrazo', 5)],
    sustitutos: ['remo-anillas', 'remo-polea-baja', 'dominada-prona'],
    instrucciones: {
      ejecucion: 'Cuerpo recto de los pies a la cabeza, tiras hasta que el pecho toque la barra.',
      consejos: ['Cuanto más horizontal el cuerpo, más difícil: empieza con la barra alta'],
    },
  },
  {
    id: 'remo-anillas',
    nombre: 'Remo en anillas',
    variante: '',
    categoria: 'Espalda',
    patron: 'tiron-horizontal',
    descripcion: 'Como el invertido, pero las anillas se mueven: hay que estabilizar y entra más core.',
    base: 'remo-invertido',
    entornos: ['calistenia', 'gym'],
    equipamiento: ['anillas'],
    dificultad: 'intermedio',
    tipos: ['compuesto', 'hipertrofia'],
    agarre: 'libre',
    medidas: ['reps'],
    musculos: [m('dorsales', 42, P), m('trapecio', 22), m('biceps', 20), m('core-profundo', 11, E), m('antebrazo', 5)],
    sustitutos: ['remo-invertido', 'remo-mancuerna'],
  },
  {
    id: 'peso-muerto',
    nombre: 'Peso muerto',
    variante: 'Convencional',
    nombreTecnico: 'Deadlift',
    categoria: 'Espalda',
    patron: 'bisagra-cadera',
    descripcion: 'Levantar la barra del suelo. Es el ejercicio que más masa muscular mueve de una vez.',
    entornos: ['gym'],
    equipamiento: ['barra', 'discos'],
    dificultad: 'avanzado',
    tipos: ['compuesto', 'fuerza'],
    agarre: 'mixto',
    medidas: ['reps', 'peso'],
    musculos: [m('erectores', 30, P), m('gluteos', 25), m('isquios', 22), m('trapecio', 13), m('antebrazo', 10)],
    variantes: ['peso-muerto-rumano'],
    sustitutos: ['peso-muerto-rumano', 'hip-thrust', 'hiperextensiones'],
    instrucciones: {
      preparacion: 'Barra pegada a la espinilla, pecho alto, espalda recta antes de tirar.',
      ejecucion: 'Empuja el suelo con las piernas y estira la cadera. La barra sube rozando las piernas.',
      respiracion: 'Coges aire abajo y aguantas durante la subida.',
      errores: ['Redondear la zona lumbar', 'Separar la barra del cuerpo', 'Tirar primero con la espalda'],
      consejos: ['Con la técnica dudosa, baja el peso: aquí no se improvisa'],
    },
  },
  {
    id: 'peso-muerto-rumano',
    nombre: 'Peso muerto rumano',
    variante: 'Piernas casi rectas',
    nombreTecnico: 'Romanian deadlift',
    categoria: 'Piernas',
    patron: 'bisagra-cadera',
    descripcion: 'La bisagra de cadera aislada: isquios y glúteo, sin levantar del suelo.',
    base: 'peso-muerto',
    entornos: ['gym', 'casa'],
    equipamiento: ['barra', 'discos', 'mancuernas'],
    dificultad: 'intermedio',
    tipos: ['compuesto', 'hipertrofia'],
    agarre: 'prono',
    medidas: ['reps', 'peso'],
    musculos: [m('isquios', 40, P), m('gluteos', 30), m('erectores', 22, E), m('antebrazo', 8)],
    sustitutos: ['curl-femoral', 'hip-thrust', 'hiperextensiones'],
  },
  {
    id: 'encogimientos-trapecio',
    nombre: 'Encogimientos',
    variante: 'Con mancuernas',
    nombreTecnico: 'Shrug',
    categoria: 'Espalda',
    patron: 'encogimiento',
    descripcion: 'Subir los hombros hacia las orejas. Va directo al trapecio.',
    entornos: ['gym', 'casa'],
    equipamiento: ['mancuernas', 'barra'],
    dificultad: 'principiante',
    tipos: ['aislamiento', 'hipertrofia'],
    agarre: 'neutro',
    medidas: ['reps', 'peso'],
    musculos: [m('trapecio', 80, P), m('antebrazo', 12), m('deltoide-lateral', 8)],
    sustitutos: ['face-pull', 'remo-barra'],
  },
  {
    id: 'pullover-mancuerna',
    nombre: 'Pullover',
    variante: 'Con mancuerna',
    categoria: 'Espalda',
    patron: 'tiron-vertical',
    descripcion: 'Llevar el peso por detrás de la cabeza estira el dorsal en todo su recorrido.',
    entornos: ['gym', 'casa'],
    equipamiento: ['mancuernas', 'banco'],
    dificultad: 'intermedio',
    tipos: ['aislamiento', 'hipertrofia'],
    agarre: 'neutro',
    medidas: ['reps', 'peso'],
    musculos: [m('dorsales', 55, P), m('pectoral-medio', 25), m('triceps', 12), m('core-profundo', 8, E)],
    sustitutos: ['jalon-al-pecho'],
  },
  {
    id: 'hiperextensiones',
    nombre: 'Hiperextensiones',
    variante: '',
    nombreTecnico: 'Back extension',
    categoria: 'Espalda',
    patron: 'bisagra-cadera',
    descripcion: 'Para la espalda baja y el glúteo, sin cargar la columna con peso encima.',
    entornos: ['gym', 'casa'],
    equipamiento: ['maquina', 'suelo'],
    dificultad: 'principiante',
    tipos: ['aislamiento'],
    medidas: ['reps'],
    musculos: [m('erectores', 55, P), m('gluteos', 27), m('isquios', 18)],
    sustitutos: ['peso-muerto-rumano', 'puente-gluteo'],
  },

  /* ── HOMBROS ───────────────────────────────────────────────────────────── */
  {
    id: 'press-militar-barra',
    nombre: 'Press militar',
    variante: 'Con barra, de pie',
    nombreTecnico: 'Overhead press',
    categoria: 'Hombros',
    patron: 'empuje-vertical',
    descripcion: 'El empuje vertical de referencia. De pie obliga a todo el cuerpo a sujetar.',
    entornos: ['gym'],
    equipamiento: ['barra', 'discos'],
    dificultad: 'intermedio',
    tipos: ['compuesto', 'fuerza', 'hipertrofia'],
    agarre: 'prono',
    medidas: ['reps', 'peso'],
    musculos: [m('deltoide-anterior', 45, P), m('deltoide-lateral', 22), m('triceps', 22), m('core-profundo', 11, E)],
    variantes: ['press-hombro-mancuernas', 'press-arnold'],
    sustitutos: ['press-hombro-mancuernas', 'press-banda-hombro', 'flexion-pino'],
    instrucciones: {
      preparacion: 'Barra a la altura de las clavículas, codos algo por delante, abdomen apretado.',
      ejecucion: 'Empuja arriba y mete un poco la cabeza cuando la barra pasa la frente.',
      errores: ['Arquear la espalda baja para llegar', 'Empujar hacia delante en vez de arriba'],
    },
  },
  {
    id: 'press-hombro-mancuernas',
    nombre: 'Press de hombro',
    variante: 'Con mancuernas',
    categoria: 'Hombros',
    patron: 'empuje-vertical',
    descripcion: 'Cada lado por su cuenta y el hombro elige su recorrido.',
    base: 'press-militar-barra',
    entornos: ['gym', 'casa'],
    equipamiento: ['mancuernas'],
    dificultad: 'principiante',
    tipos: ['compuesto', 'hipertrofia'],
    agarre: 'neutro',
    medidas: ['reps', 'peso'],
    musculos: [m('deltoide-anterior', 43, P), m('deltoide-lateral', 25), m('triceps', 20), m('core-profundo', 12, E)],
    sustitutos: ['press-militar-barra', 'press-arnold', 'press-banda-hombro'],
  },
  {
    id: 'press-arnold',
    nombre: 'Press Arnold',
    variante: 'Con giro',
    categoria: 'Hombros',
    patron: 'empuje-vertical',
    descripcion: 'Empiezas con las palmas hacia ti y giras al subir: recorre el hombro entero.',
    base: 'press-militar-barra',
    entornos: ['gym', 'casa'],
    equipamiento: ['mancuernas'],
    dificultad: 'intermedio',
    tipos: ['compuesto', 'hipertrofia'],
    agarre: 'libre',
    medidas: ['reps', 'peso'],
    musculos: [m('deltoide-anterior', 40, P), m('deltoide-lateral', 30), m('triceps', 20), m('core-profundo', 10, E)],
    sustitutos: ['press-hombro-mancuernas'],
  },
  {
    id: 'elevaciones-laterales',
    nombre: 'Elevaciones laterales',
    variante: 'Con mancuernas',
    nombreTecnico: 'Lateral raise',
    categoria: 'Hombros',
    patron: 'elevacion-hombro',
    descripcion: 'Lo único que va de verdad al deltoide lateral, que es el que da anchura.',
    entornos: ['gym', 'casa'],
    equipamiento: ['mancuernas', 'polea', 'banda'],
    dificultad: 'principiante',
    tipos: ['aislamiento', 'hipertrofia'],
    agarre: 'neutro',
    medidas: ['reps', 'peso'],
    musculos: [m('deltoide-lateral', 80, P), m('deltoide-anterior', 12), m('trapecio', 8)],
    sustitutos: ['press-hombro-mancuernas'],
    instrucciones: {
      errores: ['Usar demasiado peso y subirlo con impulso', 'Encoger los hombros al subir'],
      consejos: ['Sube hasta la altura del hombro, no más'],
    },
  },
  {
    id: 'elevaciones-frontales',
    nombre: 'Elevaciones frontales',
    variante: 'Con mancuernas',
    categoria: 'Hombros',
    patron: 'elevacion-hombro',
    descripcion: 'Aísla la parte delantera del hombro subiendo el peso por delante.',
    entornos: ['gym', 'casa'],
    equipamiento: ['mancuernas', 'banda'],
    dificultad: 'principiante',
    tipos: ['aislamiento'],
    agarre: 'prono',
    medidas: ['reps', 'peso'],
    musculos: [m('deltoide-anterior', 78, P), m('deltoide-lateral', 12), m('pectoral-superior', 10)],
    sustitutos: ['press-hombro-mancuernas'],
  },
  {
    id: 'pajaro-mancuernas',
    nombre: 'Pájaro',
    variante: 'Con mancuernas',
    nombreTecnico: 'Rear delt fly',
    categoria: 'Hombros',
    patron: 'tiron-horizontal',
    descripcion: 'Inclinado hacia delante, abre los brazos: va al hombro de detrás, el que casi nadie entrena.',
    entornos: ['gym', 'casa'],
    equipamiento: ['mancuernas', 'polea', 'banda'],
    dificultad: 'principiante',
    tipos: ['aislamiento', 'hipertrofia'],
    agarre: 'neutro',
    medidas: ['reps', 'peso'],
    musculos: [m('deltoide-posterior', 65, P), m('trapecio', 25), m('deltoide-lateral', 10)],
    sustitutos: ['face-pull', 'remo-polea-baja'],
  },
  {
    id: 'face-pull',
    nombre: 'Face pull',
    variante: 'En polea',
    categoria: 'Hombros',
    patron: 'tiron-horizontal',
    descripcion: 'Tirar de la cuerda hacia la cara. Es lo mejor que puedes hacer por la salud del hombro.',
    entornos: ['gym', 'casa'],
    equipamiento: ['polea', 'banda'],
    dificultad: 'principiante',
    tipos: ['aislamiento', 'movilidad'],
    agarre: 'neutro',
    medidas: ['reps', 'peso'],
    musculos: [m('deltoide-posterior', 50, P), m('trapecio', 35), m('biceps', 8), m('deltoide-lateral', 7)],
    sustitutos: ['pajaro-mancuernas', 'remo-banda'],
  },
  /* ── BÍCEPS ────────────────────────────────────────────────────────────── */
  {
    id: 'curl-barra',
    nombre: 'Curl con barra',
    variante: '',
    nombreTecnico: 'Barbell curl',
    categoria: 'Brazos',
    patron: 'flexion-codo',
    descripcion: 'El curl que más peso mueve, con las dos manos a la vez.',
    entornos: ['gym'],
    equipamiento: ['barra', 'discos'],
    dificultad: 'principiante',
    tipos: ['aislamiento', 'hipertrofia'],
    agarre: 'supino',
    medidas: ['reps', 'peso'],
    musculos: [m('biceps', 75, P), m('antebrazo', 20), m('deltoide-anterior', 5, E)],
    variantes: ['curl-mancuernas', 'curl-martillo', 'curl-predicador', 'curl-concentrado'],
    sustitutos: ['curl-mancuernas', 'curl-polea', 'dominada-supina'],
    instrucciones: {
      errores: ['Balancear el cuerpo para subir', 'Separar los codos del costado'],
    },
  },
  {
    id: 'curl-mancuernas',
    nombre: 'Curl con mancuernas',
    variante: '',
    categoria: 'Brazos',
    patron: 'flexion-codo',
    descripcion: 'Cada brazo por su lado, y se puede girar la muñeca al subir.',
    base: 'curl-barra',
    entornos: ['gym', 'casa'],
    equipamiento: ['mancuernas'],
    dificultad: 'principiante',
    tipos: ['aislamiento', 'hipertrofia'],
    agarre: 'supino',
    medidas: ['reps', 'peso'],
    musculos: [m('biceps', 72, P), m('antebrazo', 22), m('deltoide-anterior', 6, E)],
    sustitutos: ['curl-barra', 'curl-banda', 'curl-polea'],
  },
  {
    id: 'curl-martillo',
    nombre: 'Curl martillo',
    variante: 'Agarre neutro',
    nombreTecnico: 'Hammer curl',
    categoria: 'Brazos',
    patron: 'flexion-codo',
    descripcion: 'Con las palmas enfrentadas entra mucho más antebrazo y el braquial.',
    base: 'curl-barra',
    entornos: ['gym', 'casa'],
    equipamiento: ['mancuernas'],
    dificultad: 'principiante',
    tipos: ['aislamiento', 'hipertrofia'],
    agarre: 'neutro',
    medidas: ['reps', 'peso'],
    musculos: [m('biceps', 60, P), m('antebrazo', 35), m('deltoide-anterior', 5, E)],
    sustitutos: ['curl-mancuernas'],
  },
  {
    id: 'curl-concentrado',
    nombre: 'Curl concentrado',
    variante: 'Sentado',
    categoria: 'Brazos',
    patron: 'flexion-codo',
    unilateral: true,
    descripcion: 'Con el codo apoyado en el muslo no se puede hacer trampa con el cuerpo.',
    base: 'curl-barra',
    entornos: ['gym', 'casa'],
    equipamiento: ['mancuernas', 'banco'],
    dificultad: 'principiante',
    tipos: ['aislamiento', 'hipertrofia'],
    agarre: 'supino',
    medidas: ['reps', 'peso'],
    musculos: [m('biceps', 82, P), m('antebrazo', 18)],
    sustitutos: ['curl-predicador', 'curl-mancuernas'],
  },
  {
    id: 'curl-predicador',
    nombre: 'Curl predicador',
    variante: 'En banco Scott',
    categoria: 'Brazos',
    patron: 'flexion-codo',
    descripcion: 'El banco fija el brazo entero: todo el trabajo se queda en el bíceps.',
    base: 'curl-barra',
    entornos: ['gym'],
    equipamiento: ['banco', 'barra', 'mancuernas'],
    dificultad: 'principiante',
    tipos: ['aislamiento', 'hipertrofia'],
    agarre: 'supino',
    medidas: ['reps', 'peso'],
    musculos: [m('biceps', 80, P), m('antebrazo', 20)],
    sustitutos: ['curl-concentrado', 'curl-barra'],
  },
  {
    id: 'curl-polea',
    nombre: 'Curl en polea',
    variante: '',
    categoria: 'Brazos',
    patron: 'flexion-codo',
    descripcion: 'Tensión constante, también en la parte de arriba del recorrido.',
    entornos: ['gym'],
    equipamiento: ['polea'],
    dificultad: 'principiante',
    tipos: ['aislamiento', 'hipertrofia'],
    agarre: 'supino',
    medidas: ['reps', 'peso'],
    musculos: [m('biceps', 76, P), m('antebrazo', 19), m('deltoide-anterior', 5, E)],
    sustitutos: ['curl-barra', 'curl-banda'],
  },
  {
    id: 'curl-banda',
    nombre: 'Curl con banda',
    variante: '',
    categoria: 'Brazos',
    patron: 'flexion-codo',
    descripcion: 'El curl que se puede hacer en cualquier sitio con una banda y un pie.',
    entornos: ['casa', 'calistenia'],
    equipamiento: ['banda'],
    dificultad: 'principiante',
    tipos: ['aislamiento'],
    agarre: 'supino',
    medidas: ['reps'],
    musculos: [m('biceps', 72, P), m('antebrazo', 22), m('deltoide-anterior', 6, E)],
    sustitutos: ['curl-mancuernas', 'dominada-supina'],
  },

  /* ── TRÍCEPS ───────────────────────────────────────────────────────────── */
  {
    id: 'press-frances',
    nombre: 'Press francés',
    variante: 'Tumbado',
    nombreTecnico: 'Skull crusher',
    categoria: 'Brazos',
    patron: 'extension-codo',
    descripcion: 'Con los codos fijos hacia arriba, estira el tríceps en todo su recorrido.',
    entornos: ['gym', 'casa'],
    equipamiento: ['barra', 'mancuernas', 'banco'],
    dificultad: 'intermedio',
    tipos: ['aislamiento', 'hipertrofia'],
    agarre: 'prono',
    medidas: ['reps', 'peso'],
    musculos: [m('triceps', 85, P), m('deltoide-anterior', 10, E), m('antebrazo', 5)],
    sustitutos: ['extension-polea', 'patada-triceps', 'press-cerrado'],
    instrucciones: {
      errores: ['Mover los codos hacia delante y convertirlo en un press'],
    },
  },
  {
    id: 'extension-polea',
    nombre: 'Extensión de tríceps',
    variante: 'En polea alta',
    nombreTecnico: 'Triceps pushdown',
    categoria: 'Brazos',
    patron: 'extension-codo',
    descripcion: 'El aislamiento de tríceps más cómodo para el codo y el más fácil de hacer bien.',
    entornos: ['gym'],
    equipamiento: ['polea'],
    dificultad: 'principiante',
    tipos: ['aislamiento', 'hipertrofia'],
    agarre: 'prono',
    medidas: ['reps', 'peso'],
    musculos: [m('triceps', 88, P), m('antebrazo', 12)],
    sustitutos: ['press-frances', 'patada-triceps', 'fondos-banco'],
  },
  {
    id: 'fondos-banco',
    nombre: 'Fondos en banco',
    variante: 'De espaldas',
    nombreTecnico: 'Bench dip',
    categoria: 'Brazos',
    patron: 'empuje-vertical',
    descripcion: 'Con las manos detrás en un banco o una silla. Sale en cualquier sitio.',
    entornos: ['casa', 'calistenia', 'gym'],
    equipamiento: ['banco', 'silla'],
    dificultad: 'principiante',
    tipos: ['compuesto'],
    agarre: 'prono',
    medidas: ['reps'],
    musculos: [m('triceps', 60, P), m('deltoide-anterior', 22), m('pectoral-medio', 18)],
    sustitutos: ['fondos-paralelas-triceps', 'extension-polea', 'flexion-diamante'],
    instrucciones: {
      errores: ['Alejar mucho el cuerpo del banco y forzar el hombro'],
    },
  },
  {
    id: 'fondos-paralelas-triceps',
    nombre: 'Fondos en paralelas',
    variante: 'Vertical a tríceps',
    nombreTecnico: 'Triceps dip',
    categoria: 'Brazos',
    patron: 'empuje-vertical',
    descripcion: 'Con el torso vertical y los codos pegados, el fondo se lleva el trabajo al tríceps.',
    base: 'fondos-paralelas-pecho',
    entornos: ['gym', 'calistenia'],
    equipamiento: ['paralelas'],
    dificultad: 'intermedio',
    tipos: ['compuesto', 'hipertrofia'],
    agarre: 'neutro',
    medidas: ['reps', 'peso'],
    musculos: [m('triceps', 55, P), m('pectoral-medio', 25), m('deltoide-anterior', 15), m('core-profundo', 5, E)],
    sustitutos: ['fondos-banco', 'flexion-diamante', 'press-cerrado'],
  },
  {
    id: 'patada-triceps',
    nombre: 'Patada de tríceps',
    variante: 'Con mancuerna',
    nombreTecnico: 'Triceps kickback',
    categoria: 'Brazos',
    patron: 'extension-codo',
    unilateral: true,
    descripcion: 'Inclinado, con el codo arriba y fijo, estiras el brazo hacia atrás.',
    entornos: ['gym', 'casa'],
    equipamiento: ['mancuernas', 'banda'],
    dificultad: 'principiante',
    tipos: ['aislamiento'],
    agarre: 'neutro',
    medidas: ['reps', 'peso'],
    musculos: [m('triceps', 82, P), m('deltoide-posterior', 12), m('antebrazo', 6)],
    sustitutos: ['extension-polea', 'press-frances'],
  },
  {
    id: 'press-cerrado',
    nombre: 'Press de banca cerrado',
    variante: 'Agarre estrecho',
    nombreTecnico: 'Close grip bench press',
    categoria: 'Brazos',
    patron: 'empuje-horizontal',
    descripcion: 'El press de banca con las manos juntas: mueve peso de verdad y va al tríceps.',
    base: 'press-banca-barra',
    entornos: ['gym'],
    equipamiento: ['barra', 'discos', 'banco'],
    dificultad: 'intermedio',
    tipos: ['compuesto', 'fuerza'],
    agarre: 'cerrado',
    medidas: ['reps', 'peso'],
    musculos: [m('triceps', 50, P), m('pectoral-medio', 30), m('deltoide-anterior', 15), m('core-profundo', 5, E)],
    sustitutos: ['fondos-paralelas-triceps', 'press-frances', 'flexion-diamante'],
  },

  /* ── PIERNAS ───────────────────────────────────────────────────────────── */
  {
    id: 'sentadilla-barra',
    nombre: 'Sentadilla',
    variante: 'Con barra atrás',
    nombreTecnico: 'Back squat',
    categoria: 'Piernas',
    patron: 'sentadilla',
    descripcion: 'El ejercicio de piernas de referencia, y el que más carga aguanta.',
    entornos: ['gym'],
    equipamiento: ['barra', 'discos'],
    dificultad: 'intermedio',
    tipos: ['compuesto', 'fuerza', 'hipertrofia'],
    medidas: ['reps', 'peso'],
    musculos: [m('cuadriceps', 45, P), m('gluteos', 25), m('isquios', 12), m('erectores', 12, E), m('core-profundo', 6, E)],
    variantes: ['sentadilla-frontal', 'sentadilla-goblet'],
    sustitutos: ['prensa-piernas', 'sentadilla-goblet', 'zancada-bulgara'],
    instrucciones: {
      preparacion: 'Barra apoyada en la espalda alta, pies a la anchura de los hombros, puntas algo abiertas.',
      ejecucion: 'Baja metiendo la cadera atrás hasta que el muslo pase la paralela, y sube empujando el suelo.',
      respiracion: 'Coges aire arriba y aguantas hasta subir.',
      errores: ['Que las rodillas se metan hacia dentro', 'Levantar los talones', 'Redondear la espalda abajo'],
      consejos: ['Si no llegas abajo con la espalda recta, trabaja la movilidad de tobillo'],
    },
  },
  {
    id: 'sentadilla-frontal',
    nombre: 'Sentadilla frontal',
    variante: 'Con barra delante',
    nombreTecnico: 'Front squat',
    categoria: 'Piernas',
    patron: 'sentadilla',
    descripcion: 'Con la barra delante el torso va más vertical y entra más cuádriceps.',
    base: 'sentadilla-barra',
    entornos: ['gym'],
    equipamiento: ['barra', 'discos'],
    dificultad: 'avanzado',
    tipos: ['compuesto', 'fuerza'],
    medidas: ['reps', 'peso'],
    musculos: [m('cuadriceps', 50, P), m('gluteos', 20), m('erectores', 15, E), m('core-profundo', 10, E), m('isquios', 5)],
    sustitutos: ['sentadilla-goblet', 'sentadilla-barra'],
  },
  {
    id: 'sentadilla-goblet',
    nombre: 'Sentadilla goblet',
    variante: 'Con mancuerna al pecho',
    categoria: 'Piernas',
    patron: 'sentadilla',
    descripcion: 'Con el peso delante del pecho. Es la mejor forma de aprender a sentadillar.',
    base: 'sentadilla-barra',
    entornos: ['gym', 'casa'],
    equipamiento: ['mancuernas', 'kettlebell'],
    dificultad: 'principiante',
    tipos: ['compuesto', 'hipertrofia'],
    medidas: ['reps', 'peso'],
    musculos: [m('cuadriceps', 48, P), m('gluteos', 24), m('core-profundo', 15, E), m('isquios', 8), m('erectores', 5, E)],
    sustitutos: ['sentadilla-aire', 'sentadilla-barra', 'prensa-piernas'],
  },
  {
    id: 'sentadilla-aire',
    nombre: 'Sentadilla sin peso',
    variante: 'Al aire',
    nombreTecnico: 'Air squat',
    categoria: 'Piernas',
    patron: 'sentadilla',
    descripcion: 'La sentadilla básica, sin nada. Sirve para aprender el movimiento y para calentar.',
    base: 'sentadilla-barra',
    entornos: ['casa', 'calistenia'],
    equipamiento: ['ninguno'],
    dificultad: 'principiante',
    tipos: ['compuesto'],
    medidas: ['reps'],
    musculos: [m('cuadriceps', 45, P), m('gluteos', 30), m('isquios', 15), m('core-profundo', 10, E)],
    sustitutos: ['sentadilla-goblet', 'sentadilla-mochila', 'step-up-silla'],
  },
  {
    id: 'sentadilla-mochila',
    nombre: 'Sentadilla con mochila',
    variante: 'Peso casero',
    categoria: 'Piernas',
    patron: 'sentadilla',
    descripcion: 'Una mochila con libros es peso de verdad cuando la sentadilla sin nada se queda corta.',
    base: 'sentadilla-barra',
    entornos: ['casa'],
    equipamiento: ['mochila'],
    dificultad: 'principiante',
    tipos: ['compuesto'],
    medidas: ['reps', 'peso'],
    musculos: [m('cuadriceps', 45, P), m('gluteos', 28), m('isquios', 15), m('core-profundo', 12, E)],
    sustitutos: ['sentadilla-goblet', 'sentadilla-aire'],
  },
  {
    id: 'prensa-piernas',
    nombre: 'Prensa de piernas',
    variante: '',
    nombreTecnico: 'Leg press',
    categoria: 'Piernas',
    patron: 'sentadilla',
    descripcion: 'Mucho peso con la espalda apoyada. Buena para cargar sin técnica complicada.',
    entornos: ['gym'],
    equipamiento: ['maquina'],
    dificultad: 'principiante',
    tipos: ['compuesto', 'hipertrofia'],
    medidas: ['reps', 'peso'],
    musculos: [m('cuadriceps', 55, P), m('gluteos', 28), m('isquios', 17)],
    sustitutos: ['sentadilla-barra', 'sentadilla-goblet'],
    instrucciones: {
      errores: ['Bajar tanto que la cadera se despegue del respaldo', 'Bloquear las rodillas de golpe arriba'],
    },
  },
  {
    id: 'zancadas',
    nombre: 'Zancadas',
    variante: 'Caminando',
    nombreTecnico: 'Lunge',
    categoria: 'Piernas',
    patron: 'unilateral-pierna',
    unilateral: true,
    descripcion: 'Una pierna cada vez: reparte el trabajo y obliga a equilibrar.',
    entornos: ['gym', 'casa', 'calistenia'],
    equipamiento: ['ninguno', 'mancuernas'],
    dificultad: 'principiante',
    tipos: ['compuesto', 'hipertrofia'],
    medidas: ['reps', 'peso'],
    musculos: [m('cuadriceps', 42, P), m('gluteos', 35), m('isquios', 15), m('core-profundo', 8, E)],
    variantes: ['zancada-bulgara'],
    sustitutos: ['zancada-bulgara', 'step-up-silla', 'sentadilla-aire'],
  },
  {
    id: 'zancada-bulgara',
    nombre: 'Zancada búlgara',
    variante: 'Pie de atrás elevado',
    nombreTecnico: 'Bulgarian split squat',
    categoria: 'Piernas',
    patron: 'unilateral-pierna',
    unilateral: true,
    descripcion: 'Con el pie de atrás en un banco, casi todo el peso cae en la pierna de delante.',
    base: 'zancadas',
    entornos: ['gym', 'casa'],
    equipamiento: ['banco', 'silla', 'mancuernas'],
    dificultad: 'intermedio',
    tipos: ['compuesto', 'hipertrofia'],
    medidas: ['reps', 'peso'],
    musculos: [m('cuadriceps', 40, P), m('gluteos', 38), m('isquios', 14), m('core-profundo', 8, E)],
    sustitutos: ['zancadas', 'sentadilla-pistol'],
  },
  {
    id: 'step-up-silla',
    nombre: 'Subida a cajón',
    variante: 'En silla o banco',
    nombreTecnico: 'Step up',
    categoria: 'Piernas',
    patron: 'unilateral-pierna',
    unilateral: true,
    descripcion: 'Subir a una altura con una pierna. Fácil de graduar y muy seguro.',
    entornos: ['casa', 'gym', 'calistenia'],
    equipamiento: ['silla', 'banco', 'mancuernas'],
    dificultad: 'principiante',
    tipos: ['compuesto'],
    medidas: ['reps', 'peso'],
    musculos: [m('cuadriceps', 42, P), m('gluteos', 36), m('isquios', 14), m('core-profundo', 8, E)],
    sustitutos: ['zancadas', 'sentadilla-aire'],
  },
  {
    id: 'extension-cuadriceps',
    nombre: 'Extensión de cuádriceps',
    variante: 'En máquina',
    nombreTecnico: 'Leg extension',
    categoria: 'Piernas',
    patron: 'extension-rodilla',
    descripcion: 'Aísla el cuádriceps por completo, sin que ayude nada más.',
    entornos: ['gym'],
    equipamiento: ['maquina'],
    dificultad: 'principiante',
    tipos: ['aislamiento', 'hipertrofia'],
    medidas: ['reps', 'peso'],
    musculos: [m('cuadriceps', 92, P), m('core-profundo', 8, E)],
    sustitutos: ['sentadilla-goblet', 'prensa-piernas'],
  },
  {
    id: 'curl-femoral',
    nombre: 'Curl femoral',
    variante: 'En máquina',
    nombreTecnico: 'Leg curl',
    categoria: 'Piernas',
    patron: 'flexion-rodilla',
    descripcion: 'Aísla el isquio doblando la rodilla contra resistencia.',
    entornos: ['gym'],
    equipamiento: ['maquina'],
    dificultad: 'principiante',
    tipos: ['aislamiento', 'hipertrofia'],
    medidas: ['reps', 'peso'],
    musculos: [m('isquios', 88, P), m('gemelos', 12)],
    sustitutos: ['peso-muerto-rumano', 'hiperextensiones'],
  },
  {
    id: 'hip-thrust',
    nombre: 'Hip thrust',
    variante: 'Con barra',
    categoria: 'Piernas',
    patron: 'extension-cadera',
    descripcion: 'Empuje de cadera con la espalda apoyada. Es lo que más glúteo carga.',
    entornos: ['gym'],
    equipamiento: ['barra', 'discos', 'banco'],
    dificultad: 'intermedio',
    tipos: ['compuesto', 'hipertrofia'],
    medidas: ['reps', 'peso'],
    musculos: [m('gluteos', 60, P), m('isquios', 25), m('erectores', 10, E), m('core-profundo', 5, E)],
    variantes: ['puente-gluteo'],
    sustitutos: ['puente-gluteo', 'peso-muerto-rumano'],
  },
  {
    id: 'puente-gluteo',
    nombre: 'Puente de glúteo',
    variante: 'En el suelo',
    nombreTecnico: 'Glute bridge',
    categoria: 'Piernas',
    patron: 'extension-cadera',
    descripcion: 'El hip thrust sin nada: tumbado en el suelo y subiendo la cadera.',
    base: 'hip-thrust',
    entornos: ['casa', 'calistenia'],
    equipamiento: ['suelo', 'esterilla'],
    dificultad: 'principiante',
    tipos: ['aislamiento'],
    medidas: ['reps'],
    musculos: [m('gluteos', 62, P), m('isquios', 25), m('core-profundo', 13, E)],
    sustitutos: ['hip-thrust', 'hiperextensiones'],
  },
  {
    id: 'elevacion-talones',
    nombre: 'Elevación de talones',
    variante: 'De pie',
    nombreTecnico: 'Calf raise',
    categoria: 'Piernas',
    patron: 'flexion-plantar',
    descripcion: 'Subir de puntillas. Es lo único que va al gemelo.',
    entornos: ['gym', 'casa', 'calistenia'],
    equipamiento: ['ninguno', 'mancuernas', 'maquina'],
    dificultad: 'principiante',
    tipos: ['aislamiento'],
    medidas: ['reps', 'peso'],
    musculos: [m('gemelos', 92, P), m('core-profundo', 8, E)],
    sustitutos: ['sentadilla-salto'],
  },
  {
    id: 'sentadilla-pistol',
    nombre: 'Pistol squat',
    variante: 'A una pierna',
    categoria: 'Piernas',
    patron: 'unilateral-pierna',
    unilateral: true,
    descripcion: 'Sentadilla completa a una sola pierna. Pide fuerza, equilibrio y movilidad a la vez.',
    entornos: ['calistenia', 'casa'],
    equipamiento: ['ninguno'],
    dificultad: 'avanzado',
    tipos: ['compuesto', 'habilidad'],
    medidas: ['reps'],
    musculos: [m('cuadriceps', 45, P), m('gluteos', 30), m('core-profundo', 15, E), m('isquios', 10)],
    sustitutos: ['zancada-bulgara', 'step-up-silla'],
    progresiones: ['sentadilla-aire', 'step-up-silla', 'zancada-bulgara'],
  },
  {
    id: 'sentadilla-salto',
    nombre: 'Sentadilla con salto',
    variante: '',
    nombreTecnico: 'Jump squat',
    categoria: 'Piernas',
    patron: 'sentadilla',
    descripcion: 'Sentadilla que acaba en salto. Entrena potencia, no tamaño.',
    base: 'sentadilla-barra',
    entornos: ['casa', 'calistenia', 'gym'],
    equipamiento: ['ninguno'],
    dificultad: 'intermedio',
    tipos: ['explosivo', 'compuesto'],
    explosivo: true,
    medidas: ['reps'],
    musculos: [m('cuadriceps', 42, P), m('gluteos', 30), m('gemelos', 16), m('core-profundo', 12, E)],
    sustitutos: ['sentadilla-aire', 'burpee'],
  },
  /* ── ABDOMEN Y CORE ────────────────────────────────────────────────────── */
  {
    id: 'plancha-frontal',
    nombre: 'Plancha',
    variante: 'Frontal',
    nombreTecnico: 'Plank',
    categoria: 'Abdominales',
    patron: 'core-antiextension',
    descripcion: 'Aguantar el cuerpo recto apoyado en los antebrazos. Enseña al core a no ceder.',
    entornos: ['casa', 'calistenia', 'gym'],
    equipamiento: ['suelo', 'esterilla'],
    dificultad: 'principiante',
    tipos: ['isometrico'],
    medidas: ['tiempo'],
    musculos: [m('core-profundo', 55, P), m('recto-abdominal', 25), m('oblicuos', 12), m('deltoide-anterior', 8, E)],
    variantes: ['plancha-lateral'],
    sustitutos: ['hollow-body', 'rueda-abdominal'],
    instrucciones: {
      ejecucion: 'Cuerpo en línea recta de la cabeza a los talones, glúteo apretado, sin hundir la cadera.',
      errores: ['Subir el culo', 'Hundir la espalda baja', 'Aguantar la respiración'],
    },
  },
  {
    id: 'plancha-lateral',
    nombre: 'Plancha lateral',
    variante: 'De lado',
    nombreTecnico: 'Side plank',
    categoria: 'Abdominales',
    patron: 'core-antirrotacion',
    unilateral: true,
    descripcion: 'De lado, apoyado en un antebrazo. Va a los oblicuos.',
    base: 'plancha-frontal',
    entornos: ['casa', 'calistenia', 'gym'],
    equipamiento: ['suelo', 'esterilla'],
    dificultad: 'principiante',
    tipos: ['isometrico'],
    medidas: ['tiempo'],
    musculos: [m('oblicuos', 55, P), m('core-profundo', 30), m('deltoide-lateral', 15, E)],
    sustitutos: ['russian-twist', 'plancha-frontal'],
  },
  {
    id: 'crunch',
    nombre: 'Encogimiento abdominal',
    variante: 'En el suelo',
    nombreTecnico: 'Crunch',
    categoria: 'Abdominales',
    patron: 'flexion-tronco',
    descripcion: 'Despegar los hombros del suelo acercando las costillas a la cadera.',
    entornos: ['casa', 'gym', 'calistenia'],
    equipamiento: ['suelo', 'esterilla'],
    dificultad: 'principiante',
    tipos: ['aislamiento'],
    medidas: ['reps'],
    musculos: [m('recto-abdominal', 75, P), m('oblicuos', 15), m('core-profundo', 10)],
    sustitutos: ['elevacion-piernas-colgado', 'hollow-body'],
    instrucciones: {
      errores: ['Tirar del cuello con las manos', 'Hacerlo a tirones'],
    },
  },
  {
    id: 'elevacion-piernas-colgado',
    nombre: 'Elevación de piernas',
    variante: 'Colgado de la barra',
    nombreTecnico: 'Hanging leg raise',
    categoria: 'Abdominales',
    patron: 'flexion-cadera',
    descripcion: 'Colgado, subes las piernas. Es de los mejores para el abdomen, y además agarre.',
    entornos: ['calistenia', 'gym', 'casa'],
    equipamiento: ['barra-dominadas'],
    dificultad: 'intermedio',
    tipos: ['compuesto'],
    agarre: 'prono',
    medidas: ['reps'],
    musculos: [m('recto-abdominal', 50, P), m('core-profundo', 25), m('oblicuos', 12), m('antebrazo', 13)],
    sustitutos: ['crunch', 'l-sit', 'hollow-body'],
    instrucciones: {
      errores: ['Balancearse', 'Subir solo las rodillas cuando ya puedes con las piernas rectas'],
    },
  },
  {
    id: 'rueda-abdominal',
    nombre: 'Rueda abdominal',
    variante: 'De rodillas',
    nombreTecnico: 'Ab wheel rollout',
    categoria: 'Abdominales',
    patron: 'core-antiextension',
    descripcion: 'Estirarse hacia delante sin que la cadera ceda. Muy exigente para el core.',
    entornos: ['casa', 'gym'],
    equipamiento: ['suelo', 'esterilla'],
    dificultad: 'avanzado',
    tipos: ['compuesto'],
    medidas: ['reps'],
    musculos: [m('core-profundo', 45, P), m('recto-abdominal', 35), m('dorsales', 12), m('oblicuos', 8)],
    sustitutos: ['plancha-frontal', 'hollow-body'],
    instrucciones: {
      errores: ['Dejar que la espalda baja se arquee al estirarse'],
    },
  },
  {
    id: 'russian-twist',
    nombre: 'Giro ruso',
    variante: 'Sentado',
    nombreTecnico: 'Russian twist',
    categoria: 'Abdominales',
    patron: 'rotacion-tronco',
    descripcion: 'Sentado y girando el torso de lado a lado. Trabaja la rotación.',
    entornos: ['casa', 'gym', 'calistenia'],
    equipamiento: ['suelo', 'mancuernas'],
    dificultad: 'principiante',
    tipos: ['aislamiento'],
    medidas: ['reps', 'peso'],
    musculos: [m('oblicuos', 60, P), m('recto-abdominal', 25), m('core-profundo', 15)],
    sustitutos: ['plancha-lateral'],
  },
  {
    id: 'hollow-body',
    nombre: 'Hollow body',
    variante: 'Isométrico',
    categoria: 'Abdominales',
    patron: 'core-antiextension',
    descripcion: 'Tumbado boca arriba con brazos y piernas despegados, la espalda pegada al suelo.',
    entornos: ['calistenia', 'casa'],
    equipamiento: ['suelo', 'esterilla'],
    dificultad: 'intermedio',
    tipos: ['isometrico'],
    medidas: ['tiempo'],
    musculos: [m('core-profundo', 45, P), m('recto-abdominal', 40), m('oblicuos', 15)],
    sustitutos: ['plancha-frontal', 'l-sit'],
    instrucciones: {
      consejos: ['Si la espalda baja se despega del suelo, sube un poco las piernas'],
    },
  },
  {
    id: 'mountain-climbers',
    nombre: 'Escalador',
    variante: '',
    nombreTecnico: 'Mountain climbers',
    categoria: 'Abdominales',
    patron: 'flexion-cadera',
    descripcion: 'En posición de flexión, llevas las rodillas al pecho alternando rápido.',
    entornos: ['casa', 'calistenia'],
    equipamiento: ['suelo'],
    dificultad: 'principiante',
    tipos: ['compuesto', 'explosivo'],
    explosivo: true,
    medidas: ['reps', 'tiempo'],
    musculos: [m('core-profundo', 40, P), m('recto-abdominal', 25), m('cuadriceps', 20), m('deltoide-anterior', 15, E)],
    sustitutos: ['burpee', 'plancha-frontal'],
  },
  {
    id: 'dragon-flag',
    nombre: 'Dragon flag',
    variante: '',
    categoria: 'Abdominales',
    patron: 'core-antiextension',
    descripcion: 'Tumbado y agarrado por detrás, subes el cuerpo entero recto apoyado en los hombros.',
    entornos: ['calistenia', 'gym'],
    equipamiento: ['banco', 'suelo'],
    dificultad: 'experto',
    tipos: ['compuesto', 'habilidad'],
    medidas: ['reps', 'tiempo'],
    musculos: [m('recto-abdominal', 45, P), m('core-profundo', 35), m('oblicuos', 12), m('dorsales', 8, E)],
    sustitutos: ['hollow-body', 'elevacion-piernas-colgado'],
    progresiones: ['hollow-body', 'elevacion-piernas-colgado'],
  },
  {
    id: 'l-sit',
    nombre: 'L-sit',
    variante: 'En paralelas o suelo',
    categoria: 'Abdominales',
    patron: 'flexion-cadera',
    descripcion: 'Sostenerse con los brazos y las piernas estiradas en ángulo recto. Core y hombro a la vez.',
    entornos: ['calistenia', 'gym', 'casa'],
    equipamiento: ['paralelas', 'suelo', 'anillas'],
    dificultad: 'avanzado',
    tipos: ['isometrico', 'habilidad'],
    medidas: ['tiempo'],
    musculos: [m('core-profundo', 40, P), m('recto-abdominal', 30), m('cuadriceps', 15), m('triceps', 15, E)],
    sustitutos: ['hollow-body', 'elevacion-piernas-colgado'],
    progresiones: ['hollow-body', 'elevacion-piernas-colgado'],
    instrucciones: {
      consejos: ['Empieza con las rodillas dobladas y ve estirando según aguantes'],
    },
  },

  /* ── CUELLO ────────────────────────────────────────────────────────────── */
  {
    id: 'flexion-cuello',
    nombre: 'Flexión de cuello',
    variante: 'Tumbado boca arriba',
    categoria: 'Cuello',
    patron: 'cuello',
    descripcion: 'Levantar la cabeza tumbado boca arriba, despacio y sin peso al principio.',
    entornos: ['casa', 'gym', 'calistenia'],
    equipamiento: ['suelo', 'esterilla'],
    dificultad: 'principiante',
    tipos: ['aislamiento'],
    medidas: ['reps'],
    musculos: [m('cervical', 85, P), m('core-profundo', 15, E)],
    sustitutos: ['puente-cuello', 'extension-cuello'],
    instrucciones: {
      consejos: ['Aquí se va despacio y con poco: el cuello no perdona los tirones'],
    },
  },
  {
    id: 'extension-cuello',
    nombre: 'Extensión de cuello',
    variante: 'Tumbado boca abajo',
    categoria: 'Cuello',
    patron: 'cuello',
    descripcion: 'Levantar la cabeza tumbado boca abajo. La otra mitad del trabajo del cuello.',
    entornos: ['casa', 'gym', 'calistenia'],
    equipamiento: ['suelo', 'esterilla'],
    dificultad: 'principiante',
    tipos: ['aislamiento'],
    medidas: ['reps'],
    musculos: [m('cervical', 85, P), m('trapecio', 15)],
    sustitutos: ['flexion-cuello', 'encogimientos-trapecio'],
  },
  {
    id: 'puente-cuello',
    nombre: 'Puente de cuello',
    variante: 'Isométrico',
    categoria: 'Cuello',
    patron: 'cuello',
    descripcion: 'Aguantar apoyando la cabeza. Se hace solo cuando el cuello ya está acostumbrado.',
    entornos: ['casa', 'calistenia'],
    equipamiento: ['suelo', 'esterilla'],
    dificultad: 'avanzado',
    tipos: ['isometrico'],
    medidas: ['tiempo'],
    musculos: [m('cervical', 70, P), m('trapecio', 20), m('erectores', 10, E)],
    sustitutos: ['flexion-cuello', 'extension-cuello'],
    progresiones: ['flexion-cuello', 'extension-cuello'],
    instrucciones: {
      errores: ['Empezar por aquí sin haber hecho antes flexión y extensión'],
    },
  },

  /* ── CALISTENIA: EMPUJE ────────────────────────────────────────────────── */
  {
    id: 'flexion',
    nombre: 'Flexiones',
    variante: 'Clásicas',
    nombreTecnico: 'Push up',
    categoria: 'Pecho',
    patron: 'empuje-horizontal',
    descripcion: 'El empuje sin material. Con la técnica buena vale para toda la vida.',
    entornos: ['casa', 'calistenia', 'gym'],
    equipamiento: ['suelo'],
    dificultad: 'principiante',
    tipos: ['compuesto'],
    medidas: ['reps'],
    musculos: [m('pectoral-medio', 45, P), m('triceps', 25), m('deltoide-anterior', 20), m('core-profundo', 10, E)],
    variantes: ['flexion-diamante', 'flexion-declinada', 'flexion-explosiva', 'flexion-rodillas'],
    sustitutos: ['press-banca-barra', 'fondos-paralelas-pecho', 'flexion-rodillas'],
    instrucciones: {
      preparacion: 'Manos algo más abiertas que los hombros, cuerpo recto de la cabeza a los pies.',
      ejecucion: 'Baja hasta que el pecho casi toque el suelo, codos a unos 45 grados, y empuja.',
      errores: ['Bajar solo la cabeza', 'Hundir la cadera', 'Abrir los codos del todo'],
    },
  },
  {
    id: 'flexion-rodillas',
    nombre: 'Flexiones',
    variante: 'Apoyando rodillas',
    categoria: 'Pecho',
    patron: 'empuje-horizontal',
    descripcion: 'Con las rodillas apoyadas pesa menos. Es por donde se empieza si la normal no sale.',
    base: 'flexion',
    entornos: ['casa'],
    equipamiento: ['suelo'],
    dificultad: 'principiante',
    tipos: ['compuesto'],
    medidas: ['reps'],
    musculos: [m('pectoral-medio', 48, P), m('triceps', 25), m('deltoide-anterior', 20), m('core-profundo', 7, E)],
    sustitutos: ['flexion'],
  },
  {
    id: 'flexion-diamante',
    nombre: 'Flexiones diamante',
    variante: 'Manos juntas',
    nombreTecnico: 'Diamond push up',
    categoria: 'Brazos',
    patron: 'empuje-horizontal',
    descripcion: 'Con las manos juntas formando un triángulo, el trabajo se va al tríceps.',
    base: 'flexion',
    entornos: ['casa', 'calistenia'],
    equipamiento: ['suelo'],
    dificultad: 'intermedio',
    tipos: ['compuesto'],
    agarre: 'cerrado',
    medidas: ['reps'],
    musculos: [m('triceps', 50, P), m('pectoral-medio', 30), m('deltoide-anterior', 13), m('core-profundo', 7, E)],
    sustitutos: ['press-cerrado', 'fondos-banco', 'flexion'],
  },
  {
    id: 'flexion-declinada',
    nombre: 'Flexiones declinadas',
    variante: 'Pies elevados',
    categoria: 'Pecho',
    patron: 'empuje-horizontal',
    descripcion: 'Con los pies en una silla, el peso se va a la parte alta del pecho y al hombro.',
    base: 'flexion',
    entornos: ['casa', 'calistenia'],
    equipamiento: ['suelo', 'silla'],
    dificultad: 'intermedio',
    tipos: ['compuesto'],
    medidas: ['reps'],
    musculos: [m('pectoral-superior', 45, P), m('deltoide-anterior', 25), m('triceps', 22), m('core-profundo', 8, E)],
    sustitutos: ['press-inclinado-mancuernas', 'flexion'],
  },
  {
    id: 'flexion-explosiva',
    nombre: 'Flexiones explosivas',
    variante: 'Con despegue',
    nombreTecnico: 'Clapping push up',
    categoria: 'Pecho',
    patron: 'empuje-horizontal',
    descripcion: 'Empujar tan fuerte que las manos se despeguen. Potencia, no volumen.',
    base: 'flexion',
    entornos: ['casa', 'calistenia'],
    equipamiento: ['suelo'],
    dificultad: 'avanzado',
    tipos: ['explosivo', 'compuesto'],
    explosivo: true,
    medidas: ['reps'],
    musculos: [m('pectoral-medio', 42, P), m('triceps', 27), m('deltoide-anterior', 21), m('core-profundo', 10, E)],
    sustitutos: ['flexion', 'burpee'],
    progresiones: ['flexion', 'flexion-declinada'],
  },
  {
    id: 'fondo-anillas',
    nombre: 'Fondos en anillas',
    variante: '',
    categoria: 'Pecho',
    patron: 'empuje-vertical',
    descripcion: 'El fondo con anillas, que se mueven: hay que estabilizar todo el tiempo.',
    base: 'fondos-paralelas-pecho',
    entornos: ['calistenia', 'gym'],
    equipamiento: ['anillas'],
    dificultad: 'avanzado',
    tipos: ['compuesto', 'habilidad'],
    agarre: 'neutro',
    medidas: ['reps'],
    musculos: [m('pectoral-medio', 40, P), m('triceps', 30), m('deltoide-anterior', 18), m('core-profundo', 12, E)],
    sustitutos: ['fondos-paralelas-pecho'],
    progresiones: ['fondos-paralelas-pecho'],
  },
  {
    id: 'press-banda-hombro',
    nombre: 'Press de hombro con banda',
    variante: '',
    categoria: 'Hombros',
    patron: 'empuje-vertical',
    descripcion: 'El empuje vertical cuando no hay mancuernas: una banda pisada y a empujar.',
    entornos: ['casa', 'calistenia'],
    equipamiento: ['banda'],
    dificultad: 'principiante',
    tipos: ['compuesto'],
    medidas: ['reps'],
    musculos: [m('deltoide-anterior', 45, P), m('deltoide-lateral', 23), m('triceps', 20), m('core-profundo', 12, E)],
    sustitutos: ['press-hombro-mancuernas', 'flexion-pino'],
  },
  {
    id: 'remo-banda',
    nombre: 'Remo con banda',
    variante: '',
    categoria: 'Espalda',
    patron: 'tiron-horizontal',
    descripcion: 'El tirón horizontal con una banda anclada. Sirve de sustituto y de calentamiento.',
    entornos: ['casa', 'calistenia'],
    equipamiento: ['banda'],
    dificultad: 'principiante',
    tipos: ['compuesto'],
    agarre: 'neutro',
    medidas: ['reps'],
    musculos: [m('dorsales', 40, P), m('trapecio', 25), m('biceps', 22), m('deltoide-posterior', 13)],
    sustitutos: ['remo-invertido', 'remo-polea-baja', 'face-pull'],
  },
  {
    id: 'burpee',
    nombre: 'Burpee',
    variante: '',
    categoria: 'Cuerpo entero',
    patron: 'cuerpo-entero',
    descripcion: 'Bajar al suelo, flexión, subir y saltar. Cuerpo entero y pulso a tope.',
    entornos: ['casa', 'calistenia', 'gym'],
    equipamiento: ['suelo'],
    dificultad: 'intermedio',
    tipos: ['explosivo', 'compuesto'],
    explosivo: true,
    medidas: ['reps', 'tiempo'],
    musculos: [m('cuadriceps', 25, P), m('pectoral-medio', 20), m('deltoide-anterior', 18), m('core-profundo', 17, E), m('gluteos', 12), m('triceps', 8)],
    sustitutos: ['mountain-climbers', 'sentadilla-salto'],
  },

  /* ── CALISTENIA: HABILIDADES ───────────────────────────────────────────── */
  {
    id: 'dominada-explosiva',
    nombre: 'Dominada explosiva',
    variante: 'Con despegue',
    categoria: 'Espalda',
    patron: 'tiron-vertical',
    descripcion: 'Tirar tan fuerte que las manos lleguen a soltarse. Es el paso previo al muscle-up.',
    base: 'dominada-prona',
    entornos: ['calistenia', 'gym'],
    equipamiento: ['barra-dominadas'],
    dificultad: 'avanzado',
    tipos: ['explosivo', 'compuesto'],
    explosivo: true,
    medidas: ['reps'],
    musculos: [m('dorsales', 45, P), m('biceps', 20), m('trapecio', 15), m('antebrazo', 12), m('core-profundo', 8, E)],
    sustitutos: ['dominada-prona', 'dominada-chest-to-bar'],
    progresiones: ['dominada-prona', 'dominada-lastrada'],
  },
  {
    id: 'dominada-chest-to-bar',
    nombre: 'Dominada al pecho',
    variante: 'Chest to bar',
    categoria: 'Espalda',
    patron: 'tiron-vertical',
    descripcion: 'Subir hasta tocar la barra con el pecho, no con la barbilla.',
    base: 'dominada-prona',
    entornos: ['calistenia', 'gym'],
    equipamiento: ['barra-dominadas'],
    dificultad: 'avanzado',
    tipos: ['compuesto', 'habilidad'],
    agarre: 'prono',
    medidas: ['reps'],
    musculos: [m('dorsales', 47, P), m('biceps', 20), m('trapecio', 18), m('antebrazo', 10), m('core-profundo', 5, E)],
    sustitutos: ['dominada-prona', 'dominada-explosiva'],
    progresiones: ['dominada-prona', 'dominada-lastrada'],
  },
  {
    id: 'transicion-asistida',
    nombre: 'Transición asistida',
    variante: 'Con banda o salto',
    categoria: 'Espalda',
    patron: 'tiron-vertical',
    descripcion: 'La parte de pasar por encima de la barra, practicada con ayuda.',
    entornos: ['calistenia'],
    equipamiento: ['barra-dominadas', 'banda'],
    dificultad: 'avanzado',
    tipos: ['habilidad'],
    medidas: ['reps'],
    musculos: [m('dorsales', 35, P), m('triceps', 25), m('biceps', 18), m('pectoral-medio', 12), m('core-profundo', 10, E)],
    sustitutos: ['dominada-explosiva', 'fondos-paralelas-pecho'],
  },
  {
    id: 'muscle-up',
    nombre: 'Muscle-up',
    variante: 'En barra',
    categoria: 'Espalda',
    patron: 'tiron-vertical',
    descripcion: 'Subir por encima de la barra: dominada explosiva y fondo, encadenados.',
    entornos: ['calistenia', 'gym'],
    equipamiento: ['barra-dominadas', 'anillas'],
    dificultad: 'experto',
    tipos: ['explosivo', 'compuesto', 'habilidad'],
    explosivo: true,
    agarre: 'prono',
    medidas: ['reps'],
    musculos: [m('dorsales', 35, P), m('triceps', 22), m('pectoral-medio', 15), m('biceps', 15), m('core-profundo', 8, E), m('antebrazo', 5)],
    sustitutos: ['dominada-explosiva', 'fondos-paralelas-pecho'],
    progresiones: ['dominada-prona', 'dominada-explosiva', 'dominada-chest-to-bar', 'transicion-asistida'],
    instrucciones: {
      consejos: ['La transición es lo que cuesta, no la fuerza de tirar: practícala aparte'],
    },
  },
  {
    id: 'pino-contra-pared',
    nombre: 'Pino contra la pared',
    variante: 'Apoyado',
    nombreTecnico: 'Wall handstand',
    categoria: 'Hombros',
    patron: 'empuje-vertical',
    descripcion: 'Aguantar boca abajo con los pies en la pared. El primer paso del pino.',
    entornos: ['calistenia', 'casa'],
    equipamiento: ['suelo'],
    dificultad: 'intermedio',
    tipos: ['isometrico', 'habilidad'],
    medidas: ['tiempo'],
    musculos: [m('deltoide-anterior', 40, P), m('deltoide-lateral', 20), m('triceps', 18), m('core-profundo', 15, E), m('antebrazo', 7)],
    sustitutos: ['press-militar-barra', 'pino-libre'],
    instrucciones: {
      consejos: ['Cuerpo recto, costillas metidas: si te arqueas, baja y vuelve a colocarte'],
    },
  },
  {
    id: 'pino-libre',
    nombre: 'Pino libre',
    variante: 'Sin apoyo',
    nombreTecnico: 'Freestanding handstand',
    categoria: 'Hombros',
    patron: 'empuje-vertical',
    descripcion: 'El pino sin pared. Es equilibrio tanto como fuerza.',
    entornos: ['calistenia'],
    equipamiento: ['suelo'],
    dificultad: 'experto',
    tipos: ['isometrico', 'habilidad'],
    medidas: ['tiempo'],
    musculos: [m('deltoide-anterior', 38, P), m('core-profundo', 25, E), m('triceps', 17), m('antebrazo', 12), m('deltoide-lateral', 8)],
    sustitutos: ['pino-contra-pared'],
    progresiones: ['pino-contra-pared'],
  },
  {
    id: 'flexion-pino',
    nombre: 'Flexión en pino',
    variante: 'Contra la pared',
    nombreTecnico: 'Handstand push up',
    categoria: 'Hombros',
    patron: 'empuje-vertical',
    descripcion: 'Un press de hombro con tu propio peso, boca abajo.',
    entornos: ['calistenia'],
    equipamiento: ['suelo'],
    dificultad: 'experto',
    tipos: ['compuesto', 'habilidad'],
    medidas: ['reps'],
    musculos: [m('deltoide-anterior', 42, P), m('triceps', 30), m('deltoide-lateral', 15), m('core-profundo', 13, E)],
    sustitutos: ['press-militar-barra', 'press-hombro-mancuernas'],
    progresiones: ['pino-contra-pared', 'press-militar-barra'],
  },
  {
    id: 'tuck-planche',
    nombre: 'Tuck planche',
    variante: 'Rodillas recogidas',
    categoria: 'Hombros',
    patron: 'empuje-horizontal',
    descripcion: 'Sostenerse en el suelo con las rodillas recogidas y los pies despegados.',
    entornos: ['calistenia'],
    equipamiento: ['suelo', 'paralelas'],
    dificultad: 'avanzado',
    tipos: ['isometrico', 'habilidad'],
    medidas: ['tiempo'],
    musculos: [m('deltoide-anterior', 35, P), m('core-profundo', 25, E), m('pectoral-medio', 18), m('triceps', 12), m('antebrazo', 10)],
    sustitutos: ['l-sit', 'pino-contra-pared'],
    progresiones: ['l-sit', 'pino-contra-pared'],
  },
  {
    id: 'advanced-tuck-planche',
    nombre: 'Advanced tuck planche',
    variante: 'Espalda plana',
    base: 'tuck-planche',
    categoria: 'Hombros',
    patron: 'empuje-horizontal',
    descripcion: 'El tuck con la espalda ya plana y la cadera abierta. El salto de verdad.',
    entornos: ['calistenia'],
    equipamiento: ['suelo', 'paralelas'],
    dificultad: 'experto',
    tipos: ['isometrico', 'habilidad'],
    medidas: ['tiempo'],
    musculos: [m('deltoide-anterior', 35, P), m('core-profundo', 27, E), m('pectoral-medio', 18), m('triceps', 10), m('antebrazo', 10)],
    sustitutos: ['tuck-planche'],
    progresiones: ['tuck-planche'],
  },
  {
    id: 'straddle-planche',
    nombre: 'Straddle planche',
    variante: 'Piernas abiertas',
    base: 'tuck-planche',
    categoria: 'Hombros',
    patron: 'empuje-horizontal',
    descripcion: 'Con las piernas estiradas y abiertas, que acorta la palanca.',
    entornos: ['calistenia'],
    equipamiento: ['suelo', 'paralelas'],
    dificultad: 'experto',
    tipos: ['isometrico', 'habilidad'],
    medidas: ['tiempo'],
    musculos: [m('deltoide-anterior', 36, P), m('core-profundo', 27, E), m('pectoral-medio', 17), m('triceps', 10), m('antebrazo', 10)],
    sustitutos: ['advanced-tuck-planche'],
    progresiones: ['tuck-planche', 'advanced-tuck-planche'],
  },
  {
    id: 'full-planche',
    nombre: 'Planche',
    variante: 'Completa',
    base: 'tuck-planche',
    categoria: 'Hombros',
    patron: 'empuje-horizontal',
    descripcion: 'El cuerpo entero horizontal, sostenido solo con las manos. De lo más difícil que hay.',
    entornos: ['calistenia'],
    equipamiento: ['suelo', 'paralelas'],
    dificultad: 'experto',
    tipos: ['isometrico', 'habilidad'],
    medidas: ['tiempo'],
    musculos: [m('deltoide-anterior', 37, P), m('core-profundo', 28, E), m('pectoral-medio', 15), m('triceps', 10), m('antebrazo', 10)],
    sustitutos: ['straddle-planche'],
    progresiones: ['tuck-planche', 'advanced-tuck-planche', 'straddle-planche'],
  },
  {
    id: 'tuck-front-lever',
    nombre: 'Tuck front lever',
    variante: 'Rodillas recogidas',
    categoria: 'Espalda',
    patron: 'tiron-horizontal',
    descripcion: 'Colgado de la barra, el cuerpo horizontal con las rodillas recogidas.',
    entornos: ['calistenia'],
    equipamiento: ['barra-dominadas', 'anillas'],
    dificultad: 'avanzado',
    tipos: ['isometrico', 'habilidad'],
    medidas: ['tiempo'],
    musculos: [m('dorsales', 40, P), m('core-profundo', 27, E), m('recto-abdominal', 15), m('trapecio', 10), m('antebrazo', 8)],
    sustitutos: ['elevacion-piernas-colgado', 'dominada-prona'],
    progresiones: ['dominada-prona', 'elevacion-piernas-colgado'],
  },
  {
    id: 'advanced-tuck-front-lever',
    nombre: 'Advanced tuck front lever',
    variante: 'Espalda plana',
    base: 'tuck-front-lever',
    categoria: 'Espalda',
    patron: 'tiron-horizontal',
    descripcion: 'El tuck con la espalda ya plana, antes de estirar las piernas.',
    entornos: ['calistenia'],
    equipamiento: ['barra-dominadas', 'anillas'],
    dificultad: 'avanzado',
    tipos: ['isometrico', 'habilidad'],
    medidas: ['tiempo'],
    musculos: [m('dorsales', 40, P), m('core-profundo', 28, E), m('recto-abdominal', 14), m('trapecio', 10), m('antebrazo', 8)],
    sustitutos: ['tuck-front-lever'],
    progresiones: ['tuck-front-lever'],
  },
  {
    id: 'front-lever-una-pierna',
    nombre: 'Front lever a una pierna',
    variante: 'Una pierna estirada',
    base: 'tuck-front-lever',
    categoria: 'Espalda',
    patron: 'tiron-horizontal',
    descripcion: 'Una pierna estirada y la otra recogida. El paso intermedio.',
    entornos: ['calistenia'],
    equipamiento: ['barra-dominadas', 'anillas'],
    dificultad: 'experto',
    tipos: ['isometrico', 'habilidad'],
    medidas: ['tiempo'],
    musculos: [m('dorsales', 41, P), m('core-profundo', 28, E), m('recto-abdominal', 13), m('trapecio', 10), m('antebrazo', 8)],
    sustitutos: ['advanced-tuck-front-lever'],
    progresiones: ['tuck-front-lever', 'advanced-tuck-front-lever'],
  },
  {
    id: 'straddle-front-lever',
    nombre: 'Straddle front lever',
    variante: 'Piernas abiertas',
    base: 'tuck-front-lever',
    categoria: 'Espalda',
    patron: 'tiron-horizontal',
    descripcion: 'Con las piernas estiradas y abiertas, que quita palanca.',
    entornos: ['calistenia'],
    equipamiento: ['barra-dominadas', 'anillas'],
    dificultad: 'experto',
    tipos: ['isometrico', 'habilidad'],
    medidas: ['tiempo'],
    musculos: [m('dorsales', 42, P), m('core-profundo', 27, E), m('recto-abdominal', 13), m('trapecio', 10), m('antebrazo', 8)],
    sustitutos: ['front-lever-una-pierna'],
    progresiones: ['tuck-front-lever', 'advanced-tuck-front-lever', 'front-lever-una-pierna'],
  },
  {
    id: 'full-front-lever',
    nombre: 'Front lever',
    variante: 'Completo',
    base: 'tuck-front-lever',
    categoria: 'Espalda',
    patron: 'tiron-horizontal',
    descripcion: 'El cuerpo entero horizontal colgado de la barra. La referencia de fuerza de tirón.',
    entornos: ['calistenia'],
    equipamiento: ['barra-dominadas', 'anillas'],
    dificultad: 'experto',
    tipos: ['isometrico', 'habilidad'],
    medidas: ['tiempo'],
    musculos: [m('dorsales', 43, P), m('core-profundo', 27, E), m('recto-abdominal', 12), m('trapecio', 10), m('antebrazo', 8)],
    sustitutos: ['straddle-front-lever'],
    progresiones: ['tuck-front-lever', 'advanced-tuck-front-lever', 'front-lever-una-pierna', 'straddle-front-lever'],
  },
  {
    id: 'back-lever',
    nombre: 'Back lever',
    variante: '',
    categoria: 'Espalda',
    patron: 'tiron-horizontal',
    descripcion: 'El cuerpo horizontal pero boca abajo, con los hombros en rotación.',
    entornos: ['calistenia'],
    equipamiento: ['barra-dominadas', 'anillas'],
    dificultad: 'experto',
    tipos: ['isometrico', 'habilidad'],
    medidas: ['tiempo'],
    musculos: [m('dorsales', 35, P), m('pectoral-medio', 20), m('deltoide-anterior', 18), m('core-profundo', 17, E), m('antebrazo', 10)],
    sustitutos: ['tuck-front-lever'],
    progresiones: ['tuck-front-lever', 'advanced-tuck-front-lever'],
    instrucciones: {
      consejos: ['Aquí el hombro va en una posición forzada: calienta bien y ve poco a poco'],
    },
  },
  {
    id: 'human-flag',
    nombre: 'Human flag',
    variante: 'En barra vertical',
    categoria: 'Abdominales',
    patron: 'core-antirrotacion',
    unilateral: true,
    descripcion: 'El cuerpo horizontal agarrado a una barra vertical. Es casi todo oblicuo y dorsal.',
    entornos: ['calistenia'],
    equipamiento: ['barra-dominadas'],
    dificultad: 'experto',
    tipos: ['isometrico', 'habilidad'],
    medidas: ['tiempo'],
    musculos: [m('oblicuos', 35, P), m('dorsales', 25), m('deltoide-lateral', 18), m('core-profundo', 14, E), m('antebrazo', 8)],
    sustitutos: ['plancha-lateral', 'l-sit'],
    progresiones: ['plancha-lateral', 'l-sit', 'tuck-front-lever'],
  },
];
